### ISSUE TITLE
run the predict.py and find this error

### ISSUE THREAD

**Issue by DiracMD** [geektutu/tensorflow-tutorial-samples#1]
Traceback (most recent call last):
  File "predict.py", line 30, in <module>
    app = Predict()
  File "predict.py", line 13, in __init__
    self.cnn.model.load_weights(latest,by_name=True)
  File "/home/jinx/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 181, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/jinx/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1139, in load_weights
    if _is_hdf5_filepath(filepath):
  File "/home/jinx/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1449, in _is_hdf5_filepath
    return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by geektutu** [comment]
you need to run `python train.py first`, then run `python predict.py`
